### ISSUE TITLE
CKAN plug-ins for harvesting DKAN and Socrata-based data sources

### ISSUE THREAD

**Issue by mgalas** [mgalas/OpenDataHub#10]
Check if there are existing plug-ins/extensions to CKAN that support harvesting of non-CKAN based sources. We've discussed DKAN and Socrata as specific services that should provide harvesting capabilities.

**Comment by metaljovi** [comment]
Socrata -> Done, using an extension to harvest from /data.json on Socrata instance
DKAN -> Done, but via /data.json, not through its API
