### ISSUE TITLE
CKAN plug-in that supports geographic data views (e.g. maps)

### ISSUE THREAD

**Issue by mgalas** [mgalas/OpenDataHub#11]
data.gov.uk and similar CKAN instances are capable of visualising geographic data on a map, indicating availability of plugins that can perform the task. We want to investigate if such plugins do exist and if they do then include it in our instance.

**Comment by metaljovi** [comment]
CKAN has map view so as long as the csv file has coordinates or the dataset is a geojson file then it should be displayable. I also install additional geoview plugin but it is not always works, probably because of the quality of the dataset

**Comment by mgalas** [comment]
Thanks Fajar, that should conclude this task.
