### ISSUE TITLE
Cloudera CDH

### ISSUE THREAD

**Issue by mgalas** [mgalas/OpenDataHub#2]
Set up Cloudera CDH infrastructure on servers

**Comment by ulince** [comment]
Cloudera CDH has been setup on the cluster.
Currently two services are up and running (with no issues): Zookeeper and HDFS.
I tested reading and writing a small file to HDFS and it worked fine.

**Comment by mgalas** [comment]
Thanks @ulince this should allow us to work out data scheme.

In order to run analytics later down the line we will also need Yarn and/or Spark, can you have a go at starting those services?

**Comment by ulince** [comment]
YARN and Spark have been started as well.

**Comment by mgalas** [comment]
Are there any outstanding warnings or errors on the active services?

**Comment by ulince** [comment]
No, they're running fine at the moment.

**Comment by mgalas** [comment]
ok thanks @ulince in that case we can assume that this task is done
